version: '3.4'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
     - .:/opt/app
     - build_cache:/opt/cache
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID}
    tty: true
    stdin_open: true
    command: '/bin/bash -c "while true; do sleep 10; done;"'

volumes:
  build_cache: {}
